import test from 'node:test';
import assert from 'node:assert/strict';
import {apply,initialState,actions} from '../skills/woia-re-lease-administration/scripts/lease.mjs';
import {digest} from '../skills/woia-re-lease-administration/scripts/guard.mjs';
const now='2026-10-07T12:00:00Z', end='2026-10-08T00:00:00Z', start='2026-10-06T00:00:00Z';
function fact(kind,version=1,extra={}) {return {kind,organization:'o',target:'l',lease_version:version,status:'ACCEPTED',reference:'ref',version:'1',accepted_by:'competent-owner',source:'source',policy_revision:'p',current:true,recorded_at:start,fresh_until:end,source_authority:{organization:'o',writer:'competent-owner',source:'source',map_revision:'s',targets:['l'],fact_kinds:[kind],current:true,valid_from:start,valid_until:end},...extra};}
function terms(version=1) {const p={terms_ref:'ref',property_refs:['ref'],mandate_ref:'ref',activation_rule:fact('activation-rule',version,{required_facts:['signature','initial-money','possession','administration-transfer']})};p.accepted_version=fact('lease-version',version,{terms_digest:digest({terms_ref:p.terms_ref,property_refs:p.property_refs,mandate_ref:p.mandate_ref})});return p;}
function req(state,action,payload={}) {const r={organization:'o',target:'l',action,payload,purpose:'administration',now,expected_revision:state.revision,operation_id:`op${state.revision}`,authority:{authenticated:true,organization:'o',actor:'agent',department:state.leases.l?.writer??'leasing',purpose:'administration',policy_revision:'p',current:true,valid_from:start,valid_until:end,actions:[action],resources:['l','ref']},evidence:{source:'source',reference:'ref',version:'1',recorded_at:start,fact_kind:action,fresh_until:end},source_authority:{organization:'o',map_revision:'s',writer:'woia-re-lease-administration',source:'source',fact_kinds:[action],targets:['l'],current:true,valid_from:start,valid_until:end}};r.human_decision={principal:'human',kind:'competent-human',organization:'o',action,target:'l',payload_digest:digest(payload),policy_revision:'p',current:true,reference:'ref',valid_from:start,valid_until:end};return r;}
const created=()=>apply(initialState('o'),req(initialState('o'),'lease.create',terms())).state;
function activation() {return {accepted_facts:['signature','initial-money','possession','administration-transfer'].map(kind=>fact(kind,1,kind==='administration-transfer'?{from:'leasing',to:'asset-management'}:{}))};}
const active=()=>{const s=created();return apply(s,req(s,'lease.activate',activation())).state;};
test('independent source facts then transfer and activation',()=>{const s=active();assert.equal(s.leases.l.status,'ACTIVE');assert.equal(s.leases.l.writer,'asset-management');assert.equal(s.leases.l.versions[0].facts.length,0);});
test('immutable input / prior version retained and activation invalidated',()=>{const s=active(),before=structuredClone(s);const n=apply(s,req(s,'lease.renew',terms(2))).state;assert.deepEqual(s,before);assert.deepEqual(n.leases.l.versions[0],s.leases.l.versions[0]);assert.equal(n.leases.l.status,'DRAFT');assert.throws(()=>apply(n,req(n,'lease.activate',activation())),/EXACT_ACCEPTED_FACT/);});
test('activation cannot infer prerequisite from status',()=>{let s=created();assert.throws(()=>apply(s,req(s,'lease.activate',{accepted_facts:[]})),/EXACT_ACCEPTED_FACT/);});
test('termination has no inferred refund or vacancy',()=>{const s=active();const n=apply(s,req(s,'lease.terminate',{accepted_termination:fact('termination')}));assert.equal(n.result.deposit_released,false);assert.equal(n.result.vacancy_inferred,false);assert.throws(()=>apply(n.state,req(n.state,'lease.version',terms(2))),/LEASE_TERMINATED/);});
for(const action of ['lease.obligation.evaluate','lease.adjustment.evaluate']) test(`${action} creates only proposal`,()=>{const s=active();const r=req(s,action,{accepted_rule:fact(action.includes('obligation')?'obligation-rule':'adjustment-rule',1,{expression_ref:'ref'}),period_ref:'ref',obligation_ref:'ref'});delete r.human_decision;const n=apply(s,r);assert.equal(n.result.financial_effect,false);assert.equal(n.result.status,'PROPOSED');});
test('participant source acceptance bound to role/person',()=>{const s=created();const p={subject_ref:'ref',role:'tenant',accepted_relationship:fact('lease-participant',1,{subject_ref:'ref',role:'tenant'})};const n=apply(s,req(s,'lease.participant.link',p));assert.equal(n.state.leases.l.versions[0].participants.length,1);assert.throws(()=>apply(n.state,req(n.state,'lease.participant.link',p)),/DUPLICATE/);p.role='guarantor';assert.throws(()=>apply(s,req(s,'lease.participant.link',p)),/PARTICIPANT_ACCEPTANCE/);});
test('import creates no fictional listing history',()=>{const p=terms();p.import_source={existing_lease_ref:'ref',source_version:'source-v1',accepted_property:fact('property'),administration_mandate:fact('administration-mandate')};const s=initialState('o');const n=apply(s,req(s,'lease.create',p));assert.equal(n.state.history.length,1);assert.equal(n.state.leases.l.versions[0].import_source.source_version,'source-v1');assert.equal(n.state.leases.l.listing,undefined);});
test('operation replay current guards still apply',()=>{const s=initialState('o'),r=req(s,'lease.create',terms()),n=apply(s,r);assert.deepEqual(apply(n.state,r),n);r.authority.revoked=true;assert.throws(()=>apply(n.state,r),/CURRENT_AUTHORITY/);});
test('idempotency collision and revision conflict',()=>{const s=created();let r=req(s,'lease.version',terms(2));r.expected_revision=0;assert.throws(()=>apply(s,r),/REVISION_CONFLICT/);r=req(s,'lease.version',terms(2));r.operation_id='op0';assert.throws(()=>apply(s,r),/IDEMPOTENCY_CONFLICT/);});
for(const [label,change,error] of [
 ['org',r=>r.organization='other','ORGANIZATION_SCOPE'],['revoked',r=>r.authority.revoked=true,'CURRENT_AUTHORITY'],['future authority',r=>r.authority.valid_from=end,'CURRENT_AUTHORITY'],['scope',r=>r.authority.resources=[],'ACTION_OR_RESOURCE'],['purpose',r=>r.purpose='other','CURRENT_AUTHORITY'],['wrong writer',r=>r.authority.department='finance','CURRENT_LEASE_WRITER'],['source conflict',r=>r.source_authority.conflict=true,'CURRENT_SCOPED_SOURCE'],['source target',r=>r.source_authority.targets=[],'CURRENT_SCOPED_SOURCE'],['stale evidence',r=>r.evidence.fresh_until=start,'CURRENT_SCOPED_SOURCE'],['no human',r=>delete r.human_decision,'EXACT_HUMAN'],['future human',r=>r.human_decision.valid_from=end,'EXACT_HUMAN'],['wrong payload approval',r=>r.human_decision.payload_digest='wrong','EXACT_HUMAN'],['unowned money',r=>r.payload.payment='bypass','UNOWNED_FIELDS'],['accepted wrong version',r=>r.payload.accepted_version.lease_version=2,'EXACT_ACCEPTED_FACT'],['accepted changed terms',r=>r.payload.terms_ref='other','REFERENCE_SCOPE'],['rule unknown',r=>r.payload.activation_rule.required_facts=['pipeline'],'INVALID_ACTIVATION_RULE'],['wrong contribution owner',r=>r.payload.accepted_version.source_authority.writer='other','CONTRIBUTION_SOURCE_SCOPE'],['stale accepted terms',r=>r.payload.accepted_version.fresh_until=start,'EXACT_ACCEPTED_FACT']
]) test(`denies ${label}`,()=>{const s=initialState('o'),r=req(s,'lease.create',terms());change(r);if(r.human_decision && error!=='EXACT_HUMAN') r.human_decision.payload_digest=digest(r.payload);assert.throws(()=>apply(s,r),new RegExp(error));});
test('transferred lease rejects former writer',()=>{const s=active(),r=req(s,'lease.activate',{accepted_facts:[]});r.authority.department='leasing';assert.throws(()=>apply(s,r),/CURRENT_LEASE_WRITER/);});
test('bounded action list excludes charges, notices and deposit release',()=>{assert.equal(actions.length,9);for(const action of ['finance.charge.create','communication.external.send','payment.execute']) {const s=created();assert.throws(()=>apply(s,req(s,action)),/ACTION_OR_RESOURCE/);}});


test('physical handover after termination records actual possession without reopening',()=>{let s=active();s=apply(s,req(s,'lease.terminate',{accepted_termination:fact('termination')})).state;const n=apply(s,req(s,'lease.handover.record',{fact:fact('possession')}));assert.equal(n.state.leases.l.status,'TERMINATED');});
test('signature is not physical handover',()=>{const s=created();assert.throws(()=>apply(s,req(s,'lease.handover.record',{fact:fact('signature')})),/PHYSICAL_HANDOVER/);});

import Ajv from 'ajv';
import {readFileSync} from 'node:fs';
test('per-action schema validates correct payloads and rejects bypass fields',()=>{const schema=JSON.parse(readFileSync(new URL('../skills/woia-re-lease-administration/schemas/command.schema.json',import.meta.url),'utf8').replace(/^\uFEFF/,''));const validate=new Ajv({strict:false}).compile(schema);for(const action of actions){const payload= action==='lease.create'||action==='lease.version'||action==='lease.renew'?terms():action==='lease.activate'?activation():action==='lease.terminate'?{accepted_termination:fact('termination')}:action==='lease.participant.link'?{subject_ref:'ref',role:'tenant',accepted_relationship:fact('lease-participant')}:action==='lease.handover.record'?{fact:fact('possession')}:{accepted_rule:fact('obligation-rule'),period_ref:'ref',obligation_ref:'ref'};assert.equal(validate({action,payload}),true,JSON.stringify(validate.errors));assert.equal(validate({action,payload:{...payload,payment_execute:true}}),false);}assert.equal(validate({action:'payment.execute',payload:{}}),false);});
test('future source map cannot authorize write',()=>{const s=initialState('o'),r=req(s,'lease.create',terms());r.source_authority.valid_from=end;assert.throws(()=>apply(s,r),/CURRENT_SCOPED_SOURCE/);});
test('activation evidence retained immutably through changed version',()=>{const s=active();const proof=structuredClone(s.leases.l.activations[0]);const n=apply(s,req(s,'lease.renew',terms(2)));assert.deepEqual(n.state.leases.l.activations[0],proof);assert.equal(proof.accepted_facts.length,4);});
for (const property_refs of [undefined, [], ['ref','ref']]) test(`rejects missing/empty/duplicate property scope ${JSON.stringify(property_refs)}`,()=>{const s=initialState('o'),p=terms();p.property_refs=property_refs;assert.throws(()=>apply(s,req(s,'lease.create',p)),/LEASE_PROPERTY_SCOPE_REQUIRED/);});
